notes/mainapp/urls.py
from django.urls import path
from django.urls import include
from .views import index, EditTask, UploadFile, addComment, deleteComment, loginUp
from .views import TaskPost, TaskPostDone
from .views import addTask
from .views import task_update


app_name = 'mainapp'

urlpatterns = [
    path('', index, name='index2'),
    path('login', loginUp, name='i'),
    path('add/', addTask, name='add'),
    path('api/tasks/', TaskPost.as_view(), name='work2'),
    path('api/tasks/done/<int:pk>/<int:pkEnd>/', TaskPostDone.as_view(), name='done'),
    path('task/<int:pk>/', task_update, name='viewTask'),
    path('api/task/<int:pk>/', EditTask.as_view(), name='apiTask'),
    path('api/uploadfile/', UploadFile.as_view(), name='apiTask'),
    path('api/comments/<int:pk>/', addComment.as_view(), name='apiTask'),
    path('api/commentdelete/<int:pk>/', deleteComment.as_view(), name='apiTask'),

]

notes/notes/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('mainapp.urls', namespace='index')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

notes/mainapp/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser
from django.urls import reverse
from django.db.models import Count


class MyUser(AbstractUser):
    avatar = models.ImageField(upload_to='users_avatars', blank=True)

    def __str__(self):
        return f'{self.first_name}'


class Images(models.Model):
    file = models.FileField(upload_to='comentImages/')
    # comment_id = models.ForeignKey("Comments", on_delete=models.CASCADE, null=True)
    # отдаем URl в виде строки
    def __str__(self):
        return f'{self.file}'



class Comments(models.Model):
    author = models.ForeignKey(MyUser, on_delete=models.PROTECT)
    text = models.CharField(max_length=255)
    task_id = models.ForeignKey("Bids", on_delete=models.CASCADE, null=True)
    time_create = models.DateTimeField(auto_now_add=True, null=True)
    images = models.ManyToManyField("Images")

    def __str__(self):
        return f'{self.images}, id: {self.pk}'

class Bids(models.Model):
    author = models.ForeignKey(MyUser, on_delete=models.PROTECT, null=True, blank=True)
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=255)
    status = models.CharField(max_length=12)
    user_id = models.ForeignKey(MyUser, on_delete=models.PROTECT, related_name='worker', null=True)
    time_create = models.DateTimeField(auto_now_add=True)
    time_finish = models.DateTimeField(auto_now=False, auto_now_add=False)
    done = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.name}, id: {self.pk}'


class Bids2(models.Model):
    author = models.ForeignKey(MyUser, on_delete=models.PROTECT, null=True, blank=True)
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=255)
    status = models.CharField(max_length=12)
    user_id = models.CharField(max_length=100, blank=True)
    time_create = models.DateTimeField(auto_now_add=True)
    time_finish = models.DateTimeField(auto_now=False, auto_now_add=False)
    done = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.name}, id: {self.pk}'

notes/mainapp/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import TextInput, ModelForm, CheckboxInput, Select
from .models import *
from .models import Bids


class EditForm(forms.ModelForm):
    class Meta:
        model = Bids
        # fields = '__all__'
        fields = ['name', 'description', 'status', 'user_id', "time_finish"]

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)

class BidsEditForm(ModelForm):
    class Meta:
        model = Bids
        # fields = '__all__'
        fields = ['name', 'description', 'status', 'user_id', "time_finish"]
        # fields = ['name', 'link', 'is_to_city', 'count_lists']
#
#
# class AddPostForm(forms.Form):
#     file_tabs = models.FileField(upload_to='tabs/%Y/%m/%d/', blank=True)
#     is_able = models.BooleanField(default=False, blank=True)
#
#
# class AddBidForm(ModelForm):
#
#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         self.fields['count_lists'].empty_label = 'Кол-во страниц для сбора'
#
#     class Meta:
#         model = Bids
#         fields = ['name', 'link', 'is_to_city', 'count_lists']
#         pages = [(0, 'Кол-во страниц для сбора'), (1, 1), (5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30)]
#         widgets = {
#             "name": TextInput(attrs={
#                 'class': 'form-control'
#             }),
#             "link": TextInput(attrs={
#                 'class': 'form-control'
#             }),
#             "is_to_city": CheckboxInput(attrs={
#                 'class': 'form-check-input',
#                 'checked': 'checked'
#             }),
#             "count_lists": Select(attrs={
#                 'class': 'form-select2 form-select',
#                 'aria-label': 'Пример выбора по умолчанию'
#             }, choices=pages)
#         }
#
#     # Проверка на заполненное поле
#     def clean_count_lists(self):
#         count_lists = self.cleaned_data['count_lists']
#         if int(count_lists) == 0:
#             self.add_error('count_lists', 'Не выбрано кол-во страниц')
#             # raise ValidationError('выаывавыа')
#         return count_lists
#
#     # Проверка на длину названия
#     def clean_name(self):
#         name = self.cleaned_data['name']
#         if len(name) > 13:
#             self.add_error('name', 'Максимум 13 букв')
#         return name

notes/mainapp/views.py
import random

from django.contrib.auth import authenticate, login
from django.core.mail import send_mail
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from rest_framework.views import APIView
from rest_framework.response import Response
from .forms import *
from .serializers import BidsSerializer, MyUserSerializer, CommentsSerializer
from .models import Bids
from .models import MyUser
from .models import Comments
from .models import Images
from django.contrib.auth.models import User


# class FileDetail(generics.RetrieveAPIView):
#     serializer_class = FileSerializer
#
#     def get_object(self, queryset=None, **kwargs):
#         item = self.kwargs.get('pk')
#         return get_object_or_404(FileSave, pk=item)


class EditTask(APIView):
    def get(self, request, pk):
        edit_task = get_object_or_404(Bids, pk=pk)
        result = MyUser.objects
        serializer = MyUserSerializer(result, many=True)

        data = {
            "name": edit_task.name,
            "description": edit_task.description,
            "status": edit_task.status,
            "user_id": edit_task.user_id.pk,
            "time_finish": edit_task.time_finish,
            "done": edit_task.done,
            "users": serializer.data
        }
        return Response(data)

    def post(self, request, pk):
        edit_task = get_object_or_404(Bids, pk=pk)
        edit_task.author = get_object_or_404(MyUser, pk=request.user.id)
        edit_task.name = request.data.get('name')
        edit_task.description = request.data.get('description')
        edit_task.status = request.data.get('status')
        edit_task.user_id = get_object_or_404(MyUser, pk=request.data.get('user_id'))
        edit_task.time_finish = request.data.get('time_finish')
        if request.data.get('status') == 'done':
            edit_task.done = True
        else:
            edit_task.done = False
        edit_task.save()
        return Response({"success": "Article created successfully"})


def task_update(request, pk):
    user_id = request.user.id
    print(user_id)
    return render(request, 'mainapp/edit.html', {"pk": pk, "user_id": user_id})


def loginUp(request):
    user_id = request.user.id
    if user_id is None:
        return render(request, 'mainapp/index.html')
    else:
        return HttpResponseRedirect(reverse('index:index2'))


def index(request):
    user_id = request.user.id
    img = get_object_or_404(Images, pk=3)
    comment = get_object_or_404(Comments, pk=52)
    comment.images.remove(img)
    print(comment.images.all())

    # user = authenticate(username='admin', password='admin')
    # print(user)
    # print(type(user))
    # login(request, user)


    # if user is not None:
    # # A backend authenticated the credentials
    # else:
    # # No backend authenticated the credentials

    # hash = "%032x" % random.getrandbits(128)
    # # hash = "%032x" % hash
    # send_mail(
    #     'Авторизация вашего email',
    #     f'Ваш хеш {hash}',
    #     'info@fanfile.ru',
    #     ['fedorovich20@yandex.ru'],
    #     fail_silently=False,
    # )

    # result = get_object_or_404(FileSave, comment_id=9)
    # print(f"result: {result}")
    # file = get_object_or_404(FileSave, pk=3)
    # print(f"id comment {file.comment_id}")
    # # tast = get_object_or_404(Bids, pk=file.comment_id)
    # # print(tast)
    # print(type(user_id))
    if user_id is None:
        return HttpResponseRedirect('admin/')
    else:
        return render(request, 'mainapp/index.html')


def addTask(request):
    user_id = request.user.id
    user = get_object_or_404(MyUser, pk=user_id)
    print(user_id)
    if request.method == 'POST':
        form = BidsEditForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.author = user
            form.save()
            # ID Сохраненной задачи
            print(form.pk)
            return HttpResponseRedirect(reverse('index:index2'))

    else:
        form = BidsEditForm()
        return render(request, 'mainapp/addTask.html', {'form': form})


class TaskPost(APIView):

    def get(self, request):
        user_id = request.user.id
        print(user_id)
        result = Bids.objects.filter(done=False).order_by("time_finish")
        serializer = BidsSerializer(result, many=True)
        return Response(serializer.data)


class TaskPostDone(APIView):
    def get(self, request, pk, pkEnd):
        user_id = request.user.id
        result = Bids.objects.filter(done=True).order_by("time_finish")[pk:pkEnd]
        serializer = BidsSerializer(result, many=True)
        return Response(serializer.data)


class UploadFile(APIView):
    def post(self, request):
        # file = get_object_or_404(FileSave, pk=3)
        # data = request.data.get('file')
        # file.file = request.FILES['file']
        # file.save()
        dict = request.FILES.dict()
        for i, file in dict.items():
            images = Images()
            images.file = file
            images.save()
            print(images.pk)
            print(file)

        return Response({"success": "Article created successfully"})


class deleteComment(APIView):
    def get(self, request, pk):
        user_id = request.user.id
        comment = get_object_or_404(Comments, pk=pk)
        if user_id == comment.author.pk:
            comment.delete()
            return Response({"status": "Success"})


class addComment(APIView):
    def get(self, request, pk):
        task = get_object_or_404(Bids, pk=pk)
        result = Comments.objects.filter(task_id=task)
        serializer = CommentsSerializer(result, many=True)
        return Response(serializer.data)

    def post(self, request, pk):
        user_id = request.user.id
        user = get_object_or_404(MyUser, pk=user_id)
        task = get_object_or_404(Bids, pk=pk)
        print(request.POST)
        comment = Comments()
        comment.text = request.POST['text']
        comment.author = user
        comment.task_id = task
        comment.save()
        # Подвязываем фотки к комментам
        dict = request.FILES.dict()
        for i, file in dict.items():
            images = Images()
            images.file = file
            images.save()
            comment.images.add(images)
            comment.save()



        return Response({"success": "Article created successfully"})

    # Пример api запроса
    # with open('tabl.xlsx', 'rb') as file:
    #     url = 'http://127.0.0.1:8000/api/uploadfile/'
    #     files = {'file': file}
    #     headers = {"Content-Disposition": "attachment; filename=dog.jpg"}
    #     # передаем созданный словарь аргументу `files`
    #     resp = requests.post(url, headers=headers, files=files, )
    #     file.close()
    #     print(resp.text)

notes/mainapp/templates/mainapp/addTask.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
    <h1 class="lol" id="io">Привет мир</h1>
<!-- 
    <form action="{% url 'index:add' %}" method="post">
      {% csrf_token %} {{ form.as_p }}
      <button type="submit">Создать</button>
    </form> -->

    <form action="/add/" method="post">
        {% csrf_token %}
      <div class="mb-3">
        <label class="form-label"
          >Название задачи</label
        >
        <input
          type="text"
          class="form-control"
          name="name"
          placeholder="Название задачи"
        />
        <div class="invalid-feedback">
            Пожалуйста, введите имя пользователя.
          </div>
      </div>
      <div class="mb-3">
        <label class="form-label"
          >Описание задачи</label
        >
        <textarea
          class="form-control"
          id="exampleFormControlTextarea1"
          rows="3"
          name="description"
          placeholder="Описание задачи"
        ></textarea>
      </div>
      <label class="form-label">Статус задачи</label>
      <select class="form-select"  name="status" aria-label="Выбери статус задачи">
        <option selected>Выбери статус задачи</option>
        <option value="working">В работе</option>
        <option value="waiting">В Ожидании</option>
        <option value="done">Завершина</option>
      </select>
      <label class="form-label">Исполнитель</label>
      <select class="form-select" name="user_id" aria-label="Выбери исполнителя">
        <option selected>Выбери исполнителя</option>
        <option value="1">Андрей</option>
        <option value="2">Артем</option>
        <option value="3">Евгений</option>
      </select>
      <p>
        <label for="localdate">Дата и время: </label>
        <input type="datetime-local" id="localdate" class="form-control" name="time_finish"/>
    </p>

      <button type="submit">Создать</button>
    </form>

{% endblock %}



{% block javascript %}

<script src="{% static 'scriptAddTask3.js' %}"></script>

{% endblock %}

notes/mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">

<head>
  <meta charset="UTF-8">
  <title>Title</title>
  <link type="text/css" href="{% static 'styles2.css' %}" rel="stylesheet" />
  <link href="{% static 'core/bootstrap.min.css' %}" rel="stylesheet"
    integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
</head>

<body class="body">
  <div class="tasks">

    <nav class="navbar navbar-expand-sm navbar-dark bg-dark" aria-label="Third navbar example">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'index:index2' %}">Главная</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample03"
          aria-controls="navbarsExample03" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExample03">
          <ul class="navbar-nav me-auto mb-2 mb-sm-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">Забронировать размещение</a>
            </li>
          </ul>
          <ul class="navbar-nav mb-2 mb-sm-0">


            </li>
            <li class="nav-item">
              <a class="nav-link active">{{ user|default:'пользователь' }}</a>
            </li>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'index:index2' %}">Профиль</a>
            </li>


          </ul>
          <form role="search">
            <input class="form-control" type="search" placeholder="Search" aria-label="Search">
          </form>
        </div>
      </div>
    </nav>



    {% block content %}

    {% endblock %}


  </div>




  <script src="{% static 'core/bootstrap.bundle.min.js' %}"
    integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
    crossorigin="anonymous"></script>
  <script src="{% static 'core/axios.min.js' %}"></script>

  {% block javascript %}

  {% endblock %}

</body>

</html>

notes/mainapp/templates/mainapp/edit.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
<script>
  const authUser = {{ user_id }};
  const task_id = {{ pk }};

</script>
<!-- <div class="description" id="{{ pk }}" user_id="{{ user_id }}"></div> -->
<h1 class="lol" id="io">Привет мир</h1>

<!-- <form action="{% url 'index:add' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Создать</button>

 </form> -->

<form id="task" action="/add/" method="post">
  <div class="mb-3">
    <label class="form-label fs-3">Заголовок:</label>
    <input type="text" class="form-control fs-4" name="name" placeholder="Название задачи" />
    <div class="invalid-feedback">
      Пожалуйста, введите имя пользователя.
    </div>
  </div>
  <div class="mb-3">
    <label class="form-label fs-3">Описание задачи:</label>
    <textarea class="form-control fs-4" id="exampleFormControlTextarea1" rows="3" name="description"
      placeholder="Описание задачи"></textarea>
  </div>
  <label class="form-label fs-3">Статус задачи:</label>
  <select class="form-select fs-4" name="status" aria-label="Выбери статус задачи">
    <option selected>Выбери статус задачи</option>
    <option value="working">В работе</option>
    <option value="waiting">В Ожидании</option>
    <option value="done">Завершина</option>
  </select>
  <label class="form-label fs-3">Исполнитель:</label>
  <select class="form-select fs-4" name="user_id" aria-label="Выбери исполнителя">
    <option selected>Выбери исполнителя</option>
  </select>
  <p>
    <label for="localdate" class="form-label fs-3">Дедлайн: </label>
    <input type="datetime-local" id="localdate" class="form-control fs-4" name="time_finish" />
  </p>

  <button type="submit" class="btn btn-primary btn-lg"
    style="position: relative; left: 25%; width: 50%;">Изменить</button>
</form>

<h1 style="margin-top: 30px" style="margin-bottom: 30px">Комментарии</h1>
<div id="comments"></div>


<h1 style="margin-top: 30px">Написать комментарий</h1>
<form enctype="multipart/form-data" method="post">
  <div class="mb-3">
    <label class="form-label fs-3">Текст комментария:</label>
    <textarea class="form-control fs-4" id="exampleFormControlTextarea1" rows="3" name="textComment"
      placeholder="Текст комментария"></textarea>
    <div class="invalid-feedback">
      Пожалуйста, введите текст.
    </div>
    <label class="form-label fs-3">Выбери файл:</label>
    <input class="form-control fs-4" type="file" name="f" multiple>
    <div class="invalid-feedback">
      Выбери файл
    </div>
  </div>
  <button id="sendMessage" type="sendMessage" class="btn btn-primary btn-lg"
    style="position: relative; left: 25%; width: 50%;">Отправить</button>
</form>


{% endblock %}



{% block javascript %}
<script src="{% static 'scriptEditTask3.js' %}"></script>
{% endblock %}

notes/mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}

  <h1 class="lol" id="io">Задачи</h1>
  <div id="taskSpace">



  </div>
  <h1 class="lol">Завершенные задачи</h1>
  <div id="tasksDone"></div>
  <div id="basement" style="height: 9em; width: 100%;"></div>
  <div id="addTask"><i class="icon-plus-circle-fill"></i></div>

{% endblock %}



{% block javascript %}

<script src="{% static 'script2.js' %}"></script>

{% endblock %}

notes/mainapp/templates/mainapp/menu.html
<nav class="navbar navbar-expand-sm navbar-dark bg-dark" aria-label="Third navbar example">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'mysite:index' %}">Главная</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample03"
      aria-controls="navbarsExample03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExample03">
      <ul class="navbar-nav me-auto mb-2 mb-sm-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'acc:index' %}">Забронировать размещение</a>
        </li>
      </ul>
      <ul class="navbar-nav mb-2 mb-sm-0">

        {% if user.is_authenticated %}
        </li>
        <li class="nav-item">
          <a class="nav-link active">{{ user|default:'пользователь' }}</a>
        </li>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'auth:edit' %}">Профиль</a>
        </li>
        {% if user.is_superuser %}
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'admin:users' %}">админка</a>
        </li>
        {% endif %}
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'auth:logout' %}">Выйти</a>
        </li>

        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'auth:login' %}">войти</a>
        </li>
        {% endif %}

      </ul>
      <form role="search">
        <input class="form-control" type="search" placeholder="Search" aria-label="Search">
      </form>
    </div>
  </div>
</nav>